version: "2"

run:
  timeout: 60s
  tests: true

linters:
  enable:
    - errcheck
    - govet
    - misspell
    - revive
    - gosec
    - unconvert
    - unparam
    - goconst
    - bodyclose
    - noctx
    - nilerr
    - testifylint
    - godot

  settings:
    errcheck:
      check-type-assertions: true
      check-blank: false

    govet:
      enable:
        - shadow

    revive:
      rules:
        - name: exported
          disabled: false
          severity: warning
        - name: unexported-return
          disabled: true
          severity: warning

    misspell:
      locale: US

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
