version: "2"

run:
  timeout: 5m
  tests: true

linters:
  enable:
    - misspell
    - revive
    - gosec
    - unconvert
    - unparam
    - goconst
    - bodyclose

  settings:
    errcheck:
      check-type-assertions: true
      check-blank: false

    govet:
      enable:
        - shadow

    revive:
      rules:
        - name: exported
          disabled: false
        - name: unexported-return
          disabled: true

    gosec:
      excludes:
        - G304 # File path provided as taint input (we validate paths)
        - G204 # Subprocess with variable (we use git command intentionally)

    staticcheck:
      checks: ["all"]

    misspell:
      locale: US

  exclusions:
    paths:
      - vendor
      - web
      - test/cover

    rules:
      - path: _test\.go
        linters:
          - gosec
          - errcheck
          - goconst

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
